# Generated by Django 5.2.17 on 2026-09-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً: Ping Checker یا ARP Scanner', max_length=100, unique=True)),
                ('script_content', models.TextField(help_text="کد پایتون برای بررسی آی\u200cپی. متغیر ip_address در دسترس است. باید خروجی را در متغیر result_status قرار دهید ('available' یا 'used').")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
