# Generated by Django 5.2.17 on 2026-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_checkmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkmethod',
            name='protocol',
            field=models.CharField(choices=[('icmp', 'ICMP Ping'), ('http', 'HTTP (Port 80)'), ('https', 'HTTPS (Port 443)'), ('ssh', 'SSH (Port 22)'), ('ftp', 'FTP (Port 21)'), ('custom', 'Custom Python Script')], default='icmp', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkmethod',
            name='name',
            field=models.CharField(help_text='e.g. Default Ping Checker', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='checkmethod',
            name='script_content',
            field=models.TextField(blank=True, help_text="Only used if 'Custom Python Script' is selected. Variables available: ip_address. Must set result_status to 'available' or 'used'.", null=True),
        ),
    ]
