# Generated by Django 5.2.17 on 2026-09-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_checkmethod_protocol_alter_checkmethod_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='check_method',
            field=models.ForeignKey(blank=True, help_text='Specific discovery method for this subnet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.checkmethod'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='scan_interval_minutes',
            field=models.IntegerField(default=60, help_text='Scan interval in minutes'),
        ),
    ]
