# Generated by Django 5.2.17 on 2026-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_subnet_check_method_subnet_scan_interval_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnet',
            name='check_method',
        ),
        migrations.AddField(
            model_name='checkmethod',
            name='custom_port',
            field=models.IntegerField(blank=True, help_text="Specify port number if 'Custom TCP Port' is selected.", null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='check_methods',
            field=models.ManyToManyField(blank=True, help_text="Select one or more discovery methods for this subnet. If multiple are selected, IP is marked 'In Use' if ANY method succeeds.", to='network.checkmethod'),
        ),
        migrations.AlterField(
            model_name='checkmethod',
            name='protocol',
            field=models.CharField(choices=[('icmp', 'ICMP Ping'), ('http', 'HTTP (Port 80)'), ('https', 'HTTPS (Port 443)'), ('ssh', 'SSH (Port 22)'), ('ftp', 'FTP (Port 21)'), ('tcp_port', 'Custom TCP Port'), ('custom', 'Custom Python Script')], default='icmp', max_length=20),
        ),
    ]
