# Generated by Django 5.2.17 on 2026-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_subnet_check_method_checkmethod_custom_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='discovery_reason',
            field=models.CharField(blank=True, help_text='Method that detected this IP as in-use', max_length=255, null=True),
        ),
    ]
