# Generated by Django 5.2.17 on 2026-09-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_ipaddress_discovery_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='hostname',
            field=models.CharField(blank=True, help_text='Hostname or Server Name associated with this IP', max_length=255, null=True),
        ),
    ]
