# Generated by Django 5.2.17 on 2026-09-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_ipaddress_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='is_unique_hostname',
            field=models.BooleanField(default=False, help_text='Check this to prevent any other IP from using this hostname.', verbose_name='Unique Hostname'),
        ),
    ]
