# Generated by Django 5.2.17 on 2026-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_ipaddress_is_unique_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='check_methods',
            field=models.ManyToManyField(help_text="Select one or more discovery methods for this subnet. If multiple are selected, IP is marked 'In Use' if ANY method succeeds.", to='network.checkmethod'),
        ),
    ]
