# Generated by Django 5.2.17 on 2026-09-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_subnet_check_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('default', 'Default SaaS (Light)'), ('dark', 'Dark Mode'), ('dracula', 'Dracula (Purple/Dark)'), ('corporate', 'Corporate (Navy/Blue)')], default='default', max_length=50, verbose_name='UI Theme')),
                ('offline_timeout_hours', models.IntegerField(default=24, help_text="How many hours an IP remains 'Offline' (Gray) before automatically becoming 'Available' (Green).", verbose_name='Offline Timeout (Hours)')),
                ('auto_assign_ips', models.BooleanField(default=False, help_text='If enabled, users requesting IPs will immediately receive an available IP without requiring admin approval.', verbose_name='Automatic IP Assignment')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='last_offline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
