# Generated by Django 5.2.17 on 2026-09-29 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_systemsettings_ipaddress_last_offline_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iprequest',
            name='hostname',
            field=models.CharField(blank=True, help_text='Desired Hostname', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='iprequest',
            name='assigned_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='network.ipaddress'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('SYSTEM', 'System Process'), ('SCAN', 'Network Scan'), ('ASSIGN', 'IP Assignment')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Monitoring',
                'ordering': ['-timestamp'],
            },
        ),
    ]
