# Generated by Django 5.2.17 on 2026-09-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_iprequest_hostname_alter_iprequest_assigned_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='ip_address_padded',
            field=models.CharField(db_index=True, editable=False, max_length=15, null=True),
        ),
    ]
