# Generated by Django 5.2.17 on 2026-09-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_ipaddress_ip_address_padded'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='last_scanned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
