# Generated by Django 5.2.17 on 2026-09-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_subnet_last_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='auto_assign_range_end',
            field=models.GenericIPAddressField(blank=True, help_text='End IP of the auto-assign pool. Leave blank to use entire subnet.', null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='auto_assign_range_start',
            field=models.GenericIPAddressField(blank=True, help_text='Start IP of the auto-assign pool. Leave blank to use entire subnet.', null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='enable_auto_assign',
            field=models.BooleanField(default=True, help_text='Allow the system to automatically hand out IPs from this subnet.', verbose_name='Enable Auto-Assignment'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='System Timezone'),
        ),
    ]
