# Generated by Django 5.2.17 on 2026-09-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_subnet_auto_assign_range_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='auto_assign_range_start',
            field=models.GenericIPAddressField(blank=True, help_text='Use the graphical slider below to select the auto-assign IP boundaries.', null=True, verbose_name='IP Pool Range'),
        ),
    ]
