# Generated by Django 5.2.17 on 2026-09-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_subnet_auto_assign_range_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='manual_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Manual Date & Time'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ntp_server',
            field=models.CharField(default='pool.ntp.org', max_length=100, verbose_name='NTP Server Address'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='time_sync_mode',
            field=models.CharField(choices=[('host', 'Sync with Host/OS (Default)'), ('manual', 'Manual Time Entry'), ('ntp', 'Network Time Protocol (NTP)')], default='host', max_length=20, verbose_name='Time Synchronization Mode'),
        ),
    ]
