# Generated by Django 5.2.17 on 2026-09-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_systemsettings_manual_time_systemsettings_ntp_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprequest',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP Address'),
        ),
        migrations.AddField(
            model_name='iprequest',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='Client Browser (User-Agent)'),
        ),
    ]
