# Generated by Django 5.2.17 on 2026-09-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_iprequest_client_ip_iprequest_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Seen Online'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Seen Online'),
        ),
    ]
