# Generated by Django 5.2.17 on 2026-09-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_ipaddress_first_seen_ipaddress_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_reservation',
            field=models.BooleanField(default=False, help_text="Place assigned IPs in 'Reserved' status until they are detected online.", verbose_name='Enable IP Reservation System'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='reservation_timeout_hours',
            field=models.IntegerField(default=72, help_text='If a reserved IP is not detected online within this time, it becomes Available again.', verbose_name='Reservation Timeout (Hours)'),
        ),
    ]
