# Generated by Django 5.2.17 on 2026-09-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_systemsettings_enable_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reserved At'),
        ),
    ]
