# Generated by Django 5.2.17 on 2026-09-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_ipaddress_reserved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='alert_on_critical_offline',
            field=models.BooleanField(default=True, verbose_name='Alert when manually assigned IP goes offline'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='alert_on_subnet_full',
            field=models.BooleanField(default=True, verbose_name='Alert when subnet is >90% full'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='custom_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Custom Site Logo'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_ssl',
            field=models.BooleanField(default=False, verbose_name='Enable HTTPS (SSL)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='server_port',
            field=models.IntegerField(default=8000, verbose_name='Server Port'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ssl_cert_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SSL Certificate Path (.crt/.pem)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ssl_key_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SSL Private Key Path (.key)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Get this from @BotFather', max_length=255, null=True, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Chat/Group ID'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='theme',
            field=models.CharField(choices=[('default', 'Default SaaS (Light)'), ('darkly', 'Darkly (Sleek Dark Mode)'), ('cyborg', 'Cyborg (Black/Blue Dark)'), ('slate', 'Slate (Gray Dark Mode)'), ('cerulean', 'Cerulean (Corporate Blue)'), ('cosmo', 'Cosmo (Modern Blue)'), ('lumen', 'Lumen (Clean Light)'), ('sandstone', 'Sandstone (Warm Light)'), ('yeti', 'Yeti (Blue/Gray)'), ('flatly', 'Flatly (Flat Design)'), ('pulse', 'Pulse (Purple/Primary)'), ('simplex', 'Simplex (Minimalist)'), ('solar', 'Solar (Yellow/Dark)'), ('spacelab', 'Spacelab (Silver/Blue)'), ('superhero', 'Superhero (Blue/Gray Dark)'), ('united', 'United (Ubuntu Orange)')], default='default', max_length=50, verbose_name='UI Theme'),
        ),
    ]
