# Generated by Django 5.2.17 on 2026-09-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_systemsettings_alert_on_critical_offline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='new_ip_duration_hours',
            field=models.IntegerField(default=24, help_text="How long an IP retains the 'New' badge after discovery.", verbose_name='New IP Badge Duration (Hours)'),
        ),
    ]
