# Generated by Django 5.2.17 on 2026-09-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_systemsettings_new_ip_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='clear_all_new_ips',
            field=models.BooleanField(default=False, help_text="Check this box and save to instantly clear the 'New' status from all current IPs.", verbose_name="Clear All 'New' Badges"),
        ),
    ]
