# Generated by Django 5.2.17 on 2026-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_systemsettings_clear_all_new_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='clear_monitoring_logs',
            field=models.BooleanField(default=False, help_text='Check this box and save to instantly delete ALL monitoring (audit) logs.', verbose_name='Clear All Monitoring Logs'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='monitoring_retention_days',
            field=models.IntegerField(default=30, help_text='Number of days to keep audit logs before they are auto-deleted.', verbose_name='Monitoring Logs Retention (Days)'),
        ),
    ]
