# Generated by Django 5.2.17 on 2026-10-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_systemsettings_clear_monitoring_logs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_percent', models.FloatField()),
                ('memory_percent', models.FloatField()),
                ('disk_percent', models.FloatField()),
                ('net_bytes_sent', models.BigIntegerField(default=0)),
                ('net_bytes_recv', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Server Metric',
                'verbose_name_plural': 'Server Metrics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
