# Generated by Django 5.2.17 on 2026-10-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_servermetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='os_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC Address'),
        ),
    ]
