# Generated by Django 5.2.17 on 2026-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_ipaddress_os_name_alter_ipaddress_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='alert_mattermost',
            field=models.BooleanField(default=False, verbose_name='Enable Mattermost Alerts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='alert_sms',
            field=models.BooleanField(default=False, verbose_name='Enable SMS Alerts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='mattermost_webhook_url',
            field=models.URLField(blank=True, help_text='Incoming Webhook URL from Mattermost', max_length=500, null=True, verbose_name='Mattermost Webhook URL'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_payload_template',
            field=models.TextField(blank=True, help_text='Use {message} as placeholder. Example: {"receptor": "0912...", "template": "alert", "token": "{message}"}', null=True, verbose_name='SMS Payload (JSON Template)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_webhook_url',
            field=models.URLField(blank=True, help_text='URL to send SMS HTTP POST requests to', max_length=500, null=True, verbose_name='SMS Gateway Webhook URL'),
        ),
    ]
