# Generated by Django 5.2.17 on 2026-10-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_systemsettings_alert_mattermost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='alert_telegram',
            field=models.BooleanField(default=False, verbose_name='Enable Telegram Alerts'),
        ),
    ]
