# Generated by Django 5.2.17 on 2026-10-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_systemsettings_alert_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='alert_on_cpu_high',
            field=models.BooleanField(default=True, verbose_name='Alert on High CPU Usage (>90%)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='alert_on_disk_full',
            field=models.BooleanField(default=True, verbose_name='Alert on High Disk Usage (>90%)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='alert_on_failed_login',
            field=models.BooleanField(default=True, verbose_name='Alert on Failed Login Attempts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='alert_on_ip_in_use',
            field=models.BooleanField(default=False, verbose_name='Alert when Available IP becomes In Use'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='alert_on_memory_high',
            field=models.BooleanField(default=True, verbose_name='Alert on High Memory Usage (>90%)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='alert_on_new_ip_discovered',
            field=models.BooleanField(default=True, verbose_name='Alert on New Unmanaged IP Discovered'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='alert_on_new_ip_request',
            field=models.BooleanField(default=True, verbose_name='Alert on New IP Request'),
        ),
    ]
