# Generated by Django 5.2.17 on 2026-10-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_systemsettings_alert_on_cpu_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='alert_on_any_offline',
            field=models.BooleanField(default=False, help_text='Sends an alert when any IP (even auto-discovered devices like phones/laptops) goes offline.', verbose_name='Alert when ANY active IP goes offline'),
        ),
    ]
