# Generated by Django 5.2.17 on 2026-10-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_systemsettings_alert_on_any_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='open_ports',
            field=models.CharField(blank=True, help_text='Comma-separated list of discovered open ports', max_length=255, null=True, verbose_name='Open Ports'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('used', 'In Use'), ('offline', 'Offline (Was In Use)'), ('static', 'Static (Always In-Use)')], default='available', max_length=20),
        ),
    ]
